config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :show
  resources :groups, except: :show

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :user_groups
  has_many :users, through: :user_groups
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_groups
  has_many :groups, through: :user_groups
  accepts_nested_attributes_for :user_groups, reject_if: :reject_user_group,
                                              allow_destroy: true

  # Related to accepts_nested_attributes
  def reject_user_group(attr)
    attr['group_id'].blank?
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_assignments_controller.rb
class GroupAssignmentsController < ApplicationController
  def edit
    @group_assignment = GroupAssignment::FormObject.new(params[:id])
  end

  def update
    @group_assignment = GroupAssignment::FormObject
                          .new(params[:id], group_assignment_params[:user_groups_attributes])
    @group_assignment.save
    render :edit
  end

  private
  
  def group_assignment_params
    params.require(:group_assignment).permit(user_groups_attributes: [:group_id, :admin])
  end  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def edit
    group
  end

  def create
    @group = Group.new(group_params)
    @group.save
    redirect_to groups_path
  end

  def update
    group.update(group_params)
    redirect_to groups_path
  end

  private

  def group
    @group ||= Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.user_groups.build
  end

  def edit
    user
    user.user_groups.build unless user.user_groups.build.present?
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to users_path
  end

  def update
    user.update(user_params)
    redirect_to users_path
  end

  private

  def user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, user_groups_attributes: [:id, :user_id, :group_id, :admin, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/group_assignments/edit.html.erb
<%= form_for @group_assignment, url: group_assignment_path, html: { method: :patch } do |f| %>
  <br />
  <%= f.fields_for :user_groups do |ug| %>
    <%= ug.check_box :group_id, { checked: ug.object.id.present? }%>
    <%= ug.object.group.name %>
    <%= ug.check_box :admin %>
    Admin?
    <br />
  <% end %>
  <%= f.submit 'Assign Groups' %>
<% end %>

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: "Name" %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= simple_form_for @group do |f| %>
  <%= @group.inspect %>
  <br />
  <% if @group.user_groups.present? %>
    <%= f.fields_for :user_groups do |ugf| %>
      <% user = ugf.object.user %>
      <%= user.name rescue 'invalid ug' %>
      Admin?
      <%= ugf.check_box :admin %>
      <br />
    <% end %>
  <% else %>
    No Users in this group yet
  <% end %>
  <%= f.submit 'Update group' %>
<% end %>

app/views/groups/index.html.erb
<% @groups.each do |group| %>
  <%= group.name %>
  <%= group.id %>
  <%= link_to 'Edit', edit_group_path(group) %>
  <br />
<% end %>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HasManyWithAdditionalAttributes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: "Name" %>
  </div>
  <%= f.fields_for :user_groups do |builder| %>
    <%= render 'user_group_fields', f: builder %>
    <div id="links">
      <center><%= link_to_add_association "Add Group", f, :user_groups %></center>
    </div>
    <br>
  <% end %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_user_group_fields.html.erb
<div class="nested-fields">
  <%= f.label :gruop_id, 'Group: ' %>
  <%= f.collection_select :group_id, Group.all, :id, :name, {prompt: true}, { class: 'form-control' } %>
  <%= f.input :admin  %>
  <br>
  <center><%= link_to_remove_association "Remove", f %></center>
  <br>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.name %>
  <%= link_to 'Edit', edit_user_path(user) %>
  <br>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>